### PR TITLE
html and css added

### PR DESCRIPTION
**Pull request by rajkumardas2701**
This branch contains html, CSS and images for the project.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @rajkumardas2701 and @praz99 
### Good job you have done so far :clap: However, there are a few changes you need to make for your project to be approved.
- Update your readme file to be more detailed, [check this guide](https://github.com/microverseinc/readme-template)
- Also, write descriptive pull request detailing what you have done on the project [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- On the sidebar, use video thumbnails instead
- Validate your html code and solve the errors [use this tool](https://validator.w3.org/#validate_by_upload)
validate

### [OPTIONAl]
- Stickler is not required in this project but use this [guide to help you configure it properly](https://github.com/microverseinc/linters-config/tree/master/css)
- Practise use html5 semantics tags most of the times like nav, section, article, aside etc
### Make these changes and resubmit for another code review. Good luck.
- For assistance, contact me on slack @iamraymond
- Happy coding!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great job building this @rajkumardas2701 and @praz99 :clap: 
You have done a really fantastic job and are nearing a great end. Please consider my comment below, make the required change and request another review :ok_hand: I wish you all the best and see you at the very top :rocket: 

#### Sections are too narrow
Please consider the screenshots I have attached below, taking a good look at them, you may notice a disparity between the original and yours in terms of the section widths. The main video section, as well as the recommended video section, are a little too narrow in your case. Please look into making the required changes
screenshot
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by lekegitrepo** [comment]
## This PR is under Review by [TSE] _Temitayo Adeleke_

**Comment by lekegitrepo** [comment]
### Hi Team 👍 
**_You have done an excellent work by implementing the required changes to improve the page. The page looks great now._** ### Project Approved.

### Optional:
- **_Try to reduce the left and right margin of the page_**.

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved.

**Pull request merged**
